# setup environment
dist: jammy
language: cpp

notifications:
  email: false

branches:
  only:
  - master

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-icinga2'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux

# execute tests
install:
- sudo curl https://packages.icinga.com/icinga.key | sudo apt-key add -
- sudo echo 'deb https://packages.icinga.com/ubuntu icinga-jammy main' > /etc/apt/sources.list.d/jammy-icinga.list
- sudo apt-get update
- sudo apt-get install -y --allow-unauthenticated icinga2-bin
before_script: icinga2 --version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
