# setup environment
dist: xenial
sudo: true
language: cpp

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-icinga2"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
  - os: linux
    env: ATOM_CHANNEL=beta

# execute tests
install:
- sudo add-apt-repository -y ppa:formorer/icinga && sudo apt-get update
- sudo apt-get install -y --allow-unauthenticated icinga2-bin
before_script: icinga2 --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
