---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '**.js'
  pull_request:
    branches: [master]
    paths:
    - '**.js'

env:
  CI: true
  PACKAGES: 'language-icinga2'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        channel: [beta]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: UziTech/action-setup-atom@v3
      with:
        version: ${{ matrix.channel }}
    - name: atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: install dependencies
      run: apm install && apm install ${PACKAGES} && apm clean
    - name: lint source and spec
      run: ./node_modules/.bin/eslint lib spec || true
    - name: install icinga2
      run: sudo curl https://packages.icinga.com/icinga.key | sudo apt-key add - && sudo echo 'deb https://packages.icinga.com/ubuntu icinga-focal main' > /etc/apt/sources.list.d/focal-icinga.list && sudo apt-get update && sudo apt-get install -y --allow-unauthenticated icinga2-bin
    - name: run tests
      run: atom --test spec
